# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0002_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='etat',
            field=models.CharField(choices=[('D', 'Disponible'), ('R', 'Réservée'), ('V', 'Vendu')], default='D', max_length=1),
        ),
    ]
