# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0011_remove_annonce_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=0)),
                ('prix_enchere', models.FloatField(blank=True, default=0, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinted.Annonce')),
            ],
        ),
    ]
