# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0012_enchere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='vinted.User')),
                ('blockeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockeur', to='vinted.User')),
            ],
        ),
    ]
