# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0013_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blockeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinted.User'),
        ),
    ]
