# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0014_auto_20200803_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchere',
            name='encherisseur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinted.User'),
        ),
    ]
