# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0015_enchere_encherisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='prix_enchere',
        ),
        migrations.RemoveField(
            model_name='enchere',
            name='produit',
        ),
        migrations.AddField(
            model_name='annonce',
            name='enchere',
            field=models.ManyToManyField(blank=True, null=True, to='vinted.Enchere'),
        ),
    ]
