# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0016_auto_20200803_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enchere',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
