# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0017_auto_20200803_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='enchere',
        ),
        migrations.AddField(
            model_name='enchere',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinted.Annonce'),
        ),
    ]
