# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0018_auto_20200803_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchere',
            name='encherisseur',
        ),
        migrations.AddField(
            model_name='enchere',
            name='encherisseur',
            field=models.ManyToManyField(blank=True, null=True, to='vinted.User'),
        ),
    ]
