# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0021_auto_20200803_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mehdi', to='vinted.User'),
        ),
    ]
