# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinted', '0022_annonce_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='descript',
            field=models.CharField(max_length=1000),
        ),
    ]
